In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1, 2, 3])

In [8]:
arr

array([1, 2, 3])

In [10]:
print(arr)

[1 2 3]


# 1. Creating NumPy Arrays

In [14]:
# From Python Lists
arr1 = np.array([1, 2, 3, 4, 5])   # 1D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D - ", arr1)
print("2D - \n", arr2)

1D -  [1 2 3 4 5]
2D - 
 [[1 2 3]
 [4 5 6]]


## Creating Arrays from Scratch:

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])