In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr = np.array([1, 2, 3])

In [8]:
arr

array([1, 2, 3])

In [10]:
print(arr)

[1 2 3]


# 1. Creating NumPy Arrays

In [14]:
# From Python Lists
arr1 = np.array([1, 2, 3, 4, 5])   # 1D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D - ", arr1)
print("2D - \n", arr2)

1D -  [1 2 3 4 5]
2D - 
 [[1 2 3]
 [4 5 6]]


## Creating Arrays from Scratch:

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.full((4, 6), 8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [17]:
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [21]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

# 2. Checking Array Properties

In [31]:
myarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [32]:
print("My Array -\n", myarr)

My Array -
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
myarr.shape

(4, 3)

In [36]:
myarr.size

12

In [38]:
myarr.ndim

2

In [40]:
myarr.dtype

dtype('int64')

# 3. Changing Data Types

In [4]:
myarr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype='float32')

In [8]:
print(myarr2)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [11]:
myarr2.dtype

dtype('float32')

In [12]:
n = myarr2.astype('float64')

In [13]:
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [14]:
n.dtype

dtype('float64')

In [16]:
i = n.astype('int32')

In [17]:
i

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [19]:
i.dtype

dtype('int32')

In [21]:
print(i)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
