In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [5]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
print(flat[1])

2


In [17]:
print(flat[4])

5


In [19]:
flat[3:6]

array([4, 5, 6])

In [20]:
flat[:5]   # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [22]:
flat[3:]   # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
print(flat[-1])

12


In [28]:
arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [29]:
arr2[::2]

array([10, 30, 50, 70, 90])

In [32]:
arr2[::3]

array([ 10,  40,  70, 100])