In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [5]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
print(flat[1])

2


In [17]:
print(flat[4])

5


In [19]:
flat[3:6]

array([4, 5, 6])

In [20]:
flat[:5]   # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [22]:
flat[3:]   # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
print(flat[-1])

12


In [28]:
arr2 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [29]:
arr2[::2]

array([10, 30, 50, 70, 90])

In [32]:
arr2[::3]

array([ 10,  40,  70, 100])

### Slicing returns a view, not a copy! Changes affect the original array.

In [4]:
arrrr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
b = arrrr[3:7]

In [7]:
b

array([4, 5, 6, 7])

In [14]:
b[0] = 99

In [15]:
b

array([99,  5,  6,  7])

In [17]:
arrrr

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
c = arrrr[1:4].copy() # this is not a slice because we are using copy method to get the copy

In [19]:
c

array([ 2,  3, 99])

In [20]:
c[2] = 4

In [21]:
c

array([2, 3, 4])

In [22]:
arrrr

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Fancy Indexing (Select Multiple Elements)

In [23]:
arrrrrrr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [24]:
arrrrrrr

array([ 1, 54, 23, 53,  2,  3, 34,  5,  6])

In [26]:
arrrrrrr[[1, 4, 6]]

array([54,  2, 34])

### Boolean Masking (Filter Data)

In [28]:
arrrrrrr

array([ 1, 54, 23, 53,  2,  3, 34,  5,  6])

In [29]:
arrrrrrr[arrrrrrr > 3]

array([54, 23, 53, 34,  5,  6])

In [31]:
arrrrrrr[arrrrrrr > 50]

array([54, 53])

# Exercises for Practice

- Create a 3×3 array filled with random numbers and print its shape.

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)

(3, 3)


- Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [10]:
arr2 = np.array([1.1, 2.2, 3.3])

print(arr2.astype('int32'))

[1 2 3]


- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [13]:
arr3 = np.array([1, 2, 3, 4, 5, 6])

index = [1, 3, 5]
print(arr3[idx])

[2 4 6]


- Reshape a 1D array of size 9 into a 3×3 matrix.

In [15]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

reshaped = arr4.reshape(3, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Use boolean masking to filter numbers greater than 50 in an array.

In [17]:
arr5 = np.array([20, 73, 61, 8, 3, 42, 22, 31, 2, 90])

print(arr5[arr5 > 50])

[73 61 90]
