# 1. Understanding Axes in NumPy

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

### Summing along axes:

In [10]:
np.sum(arr, axis=0)   # Column-wise sum

array([12, 15, 18])

In [14]:
np.sum(arr, axis=1)   # Row-wise sum

array([ 6, 15, 24])

# 2. Indexing in Multidimensional Arrays

In [15]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(arr[0][1])

2


In [20]:
print(arr[0, 2])

3


In [25]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


# 3. Indexing in 3D Arrays

In [29]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
print(arr3D.shape)

(2, 2, 3)


In [33]:
print(arr3D[0, 1, 2])

6


In [35]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


# 4. Practical Example: Selecting Data Along Axes

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# get all rows of the first column
first_col = arr[:, 0]

In [40]:
print(first_col)

[1 4 7]


In [42]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
# get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]

In [45]:
print(first_rows)

[[1 2 3]
 [7 8 9]]


# 5. Changing Data Along an Axis

In [46]:
# replace all elements in column 1 with 0
arr3D[:, 0, :] = 0

In [49]:
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]
