In [2]:
import numpy as np

In [2]:
arr = np.array([23, 4, 3, 23])

In [3]:
arr.dtype

dtype('int64')

In [5]:
arr.astype('float64')

array([23.,  4.,  3., 23.])

In [6]:
arr

array([23,  4,  3, 23])

In [7]:
arr2 = np.array([23,  4,  3, 23], dtype='float64')

In [8]:
arr2

array([23.,  4.,  3., 23.])

#### Example: Memory Usage

In [14]:
arr_int64 = np.array([1, 2, 3], dtype='int64')
arr_int32 = np.array([1, 2, 3], dtype='int32')

print(arr_int64.nbytes)
print(arr_int32.nbytes)
print(arr.nbytes)
print(arr2.nbytes)

24
12
32
32


### String Data Type in NumPy

In [10]:
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')

In [11]:
print(arr)

['apple' 'banana' 'cherry']
