In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2   # vectorized operation
print(result)

[ 1  4  9 16 25]


### Broadcasting: Scaling Arrays Without Extra Memory

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
result2 = arr + 10

In [8]:
print(result2)

[11 12 13 14 15]


### Broadcasting with Arrays of Different Shapes

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

res = arr1 + arr2
print(res)

[11 22 33]
