In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2   # vectorized operation
print(result)

[ 1  4  9 16 25]


### Broadcasting: Scaling Arrays Without Extra Memory

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
result2 = arr + 10

In [8]:
print(result2)

[11 12 13 14 15]


### Broadcasting with Arrays of Different Shapes

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

res = arr1 + arr2
print(res)

[11 22 33]


### Example: Broadcasting a 2D Array and a 1D Array

In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


### Hands-on: Applying Broadcasting to Real-World Scenarios
- Example: Normalizing Data Using Broadcasting

In [11]:
# simulating a dataset (5 samples, 3 features)

data = np.array([[10, 20, 30],
                [15, 25, 35],
                [20, 30, 40],
                [25, 35, 45],
                [30, 40, 50]])

# calculating mean and standard deviation for each feature (column)

mean = data.mean(axis=0)
std = data.std(axis=0)

# normalizing the data using broadcasting

normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
