In [58]:
# Python Zip Explained
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1, l2))

[(1, 6), (2, 7), (4, 8)]

## NumPy vs. Python Lists – Performance Test

In [55]:
# Using Python List
import numpy as np
import time

size = 1_000_000_0

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
add = [x+y for x, y in zip(list1, list2)]
end = time.time()

print(add[0:10])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.7050197124481201


In [59]:
# Using Numpy Arrays
import numpy as np
import time

size = 1_000_000_0

listt1 = np.array(list(range(size)))
listt2 = np.array(list(range(size)))

start = time.time()
add = listt1 + listt2
end = time.time()

print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.035500526428222656


## Creating NumPy Arrays

In [61]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [67]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [76]:
# Checking Type

type(arr)

numpy.ndarray

In [79]:
# Checking Shape

print("Shape : ", arr.shape)

Shape :  (2, 3)


## Memory Efficiency – NumPy vs. Lists

In [87]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python List Size : ", sys.getsizeof(list_data) * len(list_data), "Bytes")
print("NumPy Array Size : ", numpy_data.nbytes, "Bytes")

Python List Size :  8056000 Bytes
NumPy Array Size :  8000 Bytes
