In [1]:
import numpy as np

In [2]:
R = np.array([
    [-1,0,-1],
    [-1,-1,100],
    [-1,-1,100]
])

Q = np.zeros((3,3))

gamma = 0.8

In [3]:
for episode in range(100):

    state = 0

    while state != 2:

        actions = np.where(R[state] != -1)[0]

        action = np.random.choice(actions)

        next_state = action

        Q[state, action] = R[state, action] + gamma * np.max(Q[next_state])

        state = next_state

In [4]:
print(Q)

[[  0.  80.   0.]
 [  0.   0. 100.]
 [  0.   0.   0.]]
